# OPTIMIZED: Build configuration for faster compilation
[build]
incremental = true
jobs = 8  # Increase parallelism

# Optimize target selection for current platform
[target."cfg(windows)"]
rustflags = ["-C", "target-cpu=native"]

[target."cfg(unix)"]
rustflags = ["-C", "target-cpu=native"]
