name: Build Windows (Simple)
on: workflow_dispatch
jobs:
  build-windows:
    runs-on: windows-2022  # Updated from deprecated windows-2019
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Tauri app
        run: npm run tauri build -- --verbose
        env:
          RUST_BACKTRACE: 1
          TAURI_BUNDLER_DEBUG: 1
          
      - name: Upload Windows executable and bundles
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: radioforms-windows-simple
          path: |
            src-tauri/target/release/radioforms.exe
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe