name: Build Windows
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install WebView2 Runtime via Chocolatey
        run: |
          echo "Installing WebView2 Runtime..."
          choco install webview2 -y --timeout 300
          echo "WebView2 installation completed"
          
      - name: Install Windows Build Tools
        run: |
          echo "Installing Windows build dependencies..."
          choco install visualstudio2022buildtools -y --timeout 600
          echo "Build tools installation completed"
          
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Tauri app with verbose output
        run: |
          echo "Starting Tauri build..."
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Rust version: $(rustc --version)"
          npm run tauri build -- --verbose
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: radioforms-windows-executable
          path: |
            src-tauri/target/release/radioforms.exe
            src-tauri/target/release/bundle/msi/*.msi