name: Build Windows
on: workflow_dispatch
jobs:
  build-windows:
    runs-on: windows-2019
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Tauri app
        run: npm run tauri build
        env:
          RUST_BACKTRACE: 1
          
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: radioforms-windows
          path: src-tauri/target/release/radioforms.exe