name: Test RadioForms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install frontend dependencies
      run: npm ci

    - name: Run frontend tests
      run: npm test

    - name: Check TypeScript compilation
      run: npm run type-check

    - name: Run ESLint
      run: npm run lint

    - name: Check frontend build
      run: npm run build

    - name: Check Rust compilation
      working-directory: src-tauri
      run: cargo check

    - name: Run Rust tests
      working-directory: src-tauri
      run: cargo test